language: ruby
sudo: false
before_install:
  # For testing purposes:
  - git config --global user.email "samuel@oriontransfer.net"
  - git config --global user.name "Samuel Williams"
rvm:
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx
env: COVERAGE=true BENCHMARK=true
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
