language: ruby
sudo: false
dist: trusty
cache: bundler
before_install:
  # For testing purposes:
  - git config --global user.email "samuel@oriontransfer.net"
  - git config --global user.name "Samuel Williams"
rvm:
  - 2.2.4
  - 2.3.2
  - 2.4.0
  - jruby-head
  - ruby-head
  - rbx-3.65
env: COVERAGE=true BENCHMARK=true
matrix:
  allow_failures:
    - rvm: rbx-3.65
    - rvm: ruby-head
    - rvm: jruby-head
