language: ruby
sudo: false
before_install:
  # For testing purposes:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - rbx-2
env: COVERAGE=true BENCHMARK=true
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
